apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mysql-secret.yaml
  - mysql-configmap-pvc-deployment.yaml
  - app-deployment-service.yaml
  - storageclass.yaml
  - static-pvc.yaml
