apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
  namespace: car-sales
spec:
  storageClassName: car-sales-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
